export const CHANGE_COLOR = "CHANGE_COLOR";
export const CHANGE_MANUFACTURE = "CHANGE_MANUFACTURE";
export const CHANGE_SORT_BY = "CHANGE_SORT_BY";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const FETCH_CARS_PENDING = "FETCH_CARS_PENDING";
export const FETCH_CARS_SUCCESS = "FETCH_CARS_SUCCESS";
export const FETCH_COLORS_SUCCESS = "FETCH_COLORS_SUCCESS";
export const FETCH_MANUFACTURERS_SUCCESS = "FETCH_MANUFACTURERS_SUCCESS";
export const FETCH_CAR_SUCCESS = "FETCH_CAR_SUCCESS";
export const ERROR = "ERROR";
